plugins {
    id 'io.micronaut.build.internal.projectgen-base'
    id "io.micronaut.build.internal.module"
}
tasks {
    prepareJavadocAggregation {
        sources.from(layout.buildDirectory.dir("generated/sources/annotationProcessor/java/main"))
    }
}
dependencies {
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}
