pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'io.micronaut.build.shared.settings' version '7.4.0'
}

rootProject.name = 'projectgen'

include 'projectgen-core'
include 'projectgen-features-javalibs'
include 'projectgen-bom'
include 'projectgen-openrewrite'
include 'projectgen-openrewrite-runner-gradle'
include 'projectgen-openrewrite-runner-maven'
include 'projectgen-test'
include 'projectgen-features-gradle'
include 'projectgen-features-maven'
include 'projectgen-springboot'
include 'projectgen-micronaut'
include 'projectgen-quarkus'
include 'projectgen-micronaut-openrewrite'

enableFeaturePreview 'TYPESAFE_PROJECT_ACCESSORS'

micronautBuild {
    useStandardizedProjectNames=true
    importMicronautCatalog()
    importMicronautCatalog("micronaut-serde")
    importMicronautCatalog("micronaut-sourcegen")
}
dependencyResolutionManagement {
    versionCatalogs {
        templateLibs {
            from(files("gradle/templates.versions.toml"))
        }
    }
}
