pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'io.micronaut.build.shared.settings' version '8.0.0-M18'
}

rootProject.name = 'projectgen'

include 'projectgen-core'
include 'projectgen-bom'
include 'test-suite-projectgen-cli'
include 'projectgen-openrewrite'
include 'projectgen-openrewrite-runner-gradle'
include 'projectgen-openrewrite-runner-maven'
include 'projectgen-test'
include 'projectgen-http-server'
include 'projectgen-micronaut'
include 'test-suite-projectgen-quarkus'
include 'projectgen-micronaut-openrewrite'
include 'test-suite-projectgen-springboot'
include 'test-suite-multi-module'
include 'test-suite-helloworld-cli'
include 'test-suite-helloworld'
include 'test-suite'
include 'test-suite-helloworld-http'
include 'test-suite-helloworld-openrewrite'
enableFeaturePreview 'TYPESAFE_PROJECT_ACCESSORS'

micronautBuild {
    useStandardizedProjectNames=true
    importMicronautCatalog()
    importMicronautCatalog("micronaut-validation")
    importMicronautCatalog("micronaut-serde")
    importMicronautCatalog("micronaut-views")
    importMicronautCatalog("micronaut-sourcegen")
    importMicronautCatalog("micronaut-picocli")
    importMicronautCatalog("micronaut-logging")
}
dependencyResolutionManagement {
    versionCatalogs {
        templateLibs {
            from(files("gradle/templates.versions.toml"))
        }
    }
}
