[versions]

micronaut = "5.1.6"
micronaut-platform = "5.0.5"
rewrite-recipe-bom = "3.35.0"
micronaut-serialization = "3.1.0"
micronaut-views = "6.1.0"
micronaut-sourcegen = "2.1.0"
micronaut-logging = "2.1.0"
micronaut-validation = "5.1.0"
micronaut-picocli = "6.1.0"
apache-commons-compress = "1.28.0"
snakeyaml = "2.4"
typesafeconfig = "1.4.9"
maven-invoker = "3.3.0"
gradle-tooling-api = "9.6.1"
sonatype-scan = "3.0.0"
java-diff-utils = "4.16"
commons-lang3 = "3.20.0"

[libraries]
java-diff-utils = { module = 'io.github.java-diff-utils:java-diff-utils', version.ref = 'java-diff-utils' }
micronaut-validation = { module = 'io.micronaut.validation:micronaut-validation-bom', version.ref = 'micronaut-validation' }
micronaut-views = { module = 'io.micronaut.views:micronaut-views-bom', version.ref = 'micronaut-views' }
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-logging = { module = 'io.micronaut.logging:micronaut-logging-bom', version.ref = 'micronaut-logging' }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serialization" }
micronaut-sourcegen = { module = "io.micronaut.sourcegen:micronaut-sourcegen-bom", version.ref = "micronaut-sourcegen" }
micronaut-picocli = { module = "io.micronaut.picocli:micronaut-picocli-bom", version.ref = "micronaut-picocli" }
typesafeconfig = { module = "com.typesafe:config", version.ref = "typesafeconfig" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
apache-commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "apache-commons-compress" }
rewrite-recipe-bom = { module = "org.openrewrite.recipe:rewrite-recipe-bom", version.ref = "rewrite-recipe-bom" }
rewrite-core = { module = "org.openrewrite:rewrite-core" }
rewrite-properties = { module = "org.openrewrite:rewrite-properties" }
rewrite-gradle = { module = "org.openrewrite:rewrite-gradle" }
rewrite-java-dependencies = { module = "org.openrewrite.recipe:rewrite-java-dependencies" }
rewrite-maven = { module = "org.openrewrite:rewrite-maven" }
rewrite-java = { module = "org.openrewrite:rewrite-java" }
rewrite-java17 = { module = "org.openrewrite:rewrite-java-17" }
rewrite-yaml = { module = "org.openrewrite:rewrite-yaml" }
rewrite-test = { module = "org.openrewrite:rewrite-test" }
maven-invoker = { module = "org.apache.maven.shared:maven-invoker", version.ref = "maven-invoker" }
gradle-tooling-api = { module = "org.gradle:gradle-tooling-api", version.ref = "gradle-tooling-api" }
sonatype-scan = { module = "org.sonatype.gradle.plugins:scan-gradle-plugin", version.ref = "sonatype-scan" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }

[bundles]

[plugins]

