type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.cassandra-config
displayName: Add Cassandra Micrometer configuration
preconditions:
  - io.micronaut.starter.openrewrite.recipes.FindApplicationProperties
recipeList:
  - org.openrewrite.properties.AddProperty:
      property: cassandra.default.basic.contact-points[0]
      value: localhost:9042
