type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.cassandra-config-testresources
displayName: Add Cassandra Micrometer configuration
preconditions:
  - io.micronaut.starter.openrewrite.recipes.FindApplicationProperties
recipeList:
  - org.openrewrite.properties.AddProperty:
      property: test-resources.containers.cassandra.startup-timeout
      value: 600s
  - org.openrewrite.properties.AddProperty:
      property: test-resources.containers.cassandra.image-name
      value: cassandra
  - org.openrewrite.properties.AddProperty:
      property: test-resources.containers.cassandra.exposed-ports[0].cassandra.port
      value: 9042
  - org.openrewrite.properties.AddProperty:
      property: cassandra.default.basic.contact-points[0]
      value: localhost:${cassandra.port}
