type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.data-config-sqlserver
displayName: Add Data SqlServer configuration
preconditions:
  - io.micronaut.starter.openrewrite.recipes.FindApplicationProperties
recipeList:
  - org.openrewrite.properties.AddProperty:
      property: datasources.default.dialect
      value: SQL_SERVER
