type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.data-config-oracle
displayName: Add Data Oracle configuration
recipeList:
  - io.micronaut.starter.feature.create-application-properties
  - io.micronaut.starter.feature.data-config-oracle.config
---
type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.data-config-oracle.config
displayName: Add Data Oracle configuration
preconditions:
  - io.micronaut.starter.openrewrite.recipes.FindApplicationProperties
recipeList:
  - org.openrewrite.properties.AddProperty:
      property: datasources.default.dialect
      value: ORACLE
