type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.data-config-mysql
displayName: Add Data Mysql configuration
recipeList:
  - io.micronaut.starter.feature.create-application-properties
  - io.micronaut.starter.feature.data-config-mysql.config
---
type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.data-config-mysql.config
displayName: Add Data Mysql configuration
preconditions:
  - io.micronaut.starter.openrewrite.recipes.FindApplicationProperties
recipeList:
  - org.openrewrite.properties.AddProperty:
      property: datasources.default.dialect
      value: MYSQL
