type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.oci-config-profile
displayName: Add Oci Config Profile Configuration
recipeList:
  - io.micronaut.starter.feature.create-application-properties
  - io.micronaut.starter.feature.oci-config-profile.config
---
type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.oci-config-profile.config
displayName: Add Oci Config Profile Configuration
preconditions:
  - io.micronaut.starter.openrewrite.recipes.FindApplicationProperties
recipeList:
  - org.openrewrite.properties.AddProperty:
      property: oci.config.profile
      value: DEFAULT
