type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.openapi-processor
displayName: Add Openapi Annotation Processor
recipeList:
  - io.micronaut.starter.feature.openapi-processor.maven
  - io.micronaut.starter.feature.openapi-processor.gradle
---
type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.openapi-processor.maven
displayName: Add Openapi annotations Processor to the Maven compiler plugin
recipeList:
  - org.openrewrite.maven.AddAnnotationProcessor:
      groupId: io.micronaut.openapi
      artifactId: micronaut-openapi
      version: ${micronaut.openapi.version}
---
type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.openapi-processor.gradle
displayName: Add Openapi annotations Processor dependency to a Gradle Build
recipeList:
  - org.openrewrite.gradle.AddDependency:
      groupId: io.micronaut.openapi
      artifactId: micronaut-openapi
      configuration: annotationProcessor
