type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.r2dbc-config-postgresql
displayName: Add R2dbc Postgresql driver configuration
recipeList:
  - io.micronaut.starter.feature.create-application-properties
  - io.micronaut.starter.feature.r2dbc-config-postgresql.config
---
type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.r2dbc-config-postgresql.config
displayName: Add R2dbc Postgresql driver configuration
preconditions:
  - io.micronaut.starter.openrewrite.recipes.FindApplicationProperties
recipeList:
  - org.openrewrite.properties.AddProperty:
      property: r2dbc.datasources.default.dialect
      value: POSTGRES
  - org.openrewrite.properties.AddProperty:
      property: r2dbc.datasources.default.db-type
      value: postgres
