type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.r2dbc-configuration
displayName: Add R2dbc configuration
preconditions:
  - io.micronaut.starter.openrewrite.recipes.FindApplicationProperties
recipeList:
  - org.openrewrite.properties.AddProperty:
      property: r2dbc.datasources.default.dialect
      value: H2
