type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.r2dbc-config-sqlserver
displayName: Add R2dbc Sqlserver driver configuration
preconditions:
  - io.micronaut.starter.openrewrite.recipes.FindApplicationProperties
recipeList:
  - org.openrewrite.properties.AddProperty:
      property: r2dbc.datasources.default.dialect
      value: SQL_SERVER
  - org.openrewrite.properties.AddProperty:
      property: r2dbc.datasources.default.db-type
      value: mssql
  - org.openrewrite.properties.AddProperty:
      property: test-resources.containers.mssql.accept-license
      value: false
