type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.r2dbc-config-h2
displayName: Add R2dbc H2 driver configuration
preconditions:
  - io.micronaut.starter.openrewrite.recipes.FindApplicationProperties
recipeList:
  - org.openrewrite.properties.AddProperty:
      property: r2dbc.datasources.default.url
      value: r2dbc:h2:mem:///testdb;DB_CLOSE_ON_EXIT=FALSE
  - org.openrewrite.properties.AddProperty:
      property: r2dbc.datasources.default.username
      value: sa
  - org.openrewrite.properties.AddProperty:
      property: r2dbc.datasources.default.password
      value: ""
