type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.security-jwt-config
displayName: Add Security Jwt configuration
preconditions:
  - io.micronaut.starter.openrewrite.recipes.FindApplicationProperties
recipeList:
  - org.openrewrite.properties.AddProperty:
      property: micronaut.security.token.jwt.signatures.secret.generator.secret
      value: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
