micronaut.application.name=micronaut-monolith
micronaut.router.static-resources.javascripts.paths=classpath:assets/javascripts
micronaut.router.static-resources.javascripts.mapping=/assets/javascripts/**
micronaut.router.static-resources.stylesheets.paths=classpath:assets/stylesheets
micronaut.router.static-resources.stylesheets.mapping=/assets/stylesheets/**
projectgen.controllers.features.enabled=false
