type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.chatbots-basecamp-configuration
displayName: Add Chatbots Basecamp configuration
preconditions:
  - io.micronaut.starter.openrewrite.recipes.FindApplicationProperties
recipeList:
  - org.openrewrite.properties.AddProperty:
      property: micronaut.chatbots.folder
      value: botcommands
