type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.coherence-distributed-configuration
displayName: Add Coherence Distributed Configuration dependency and link to README
recipeList:
  - io.micronaut.starter.feature.coherence-distributed-configuration.dependencies
  - io.micronaut.starter.feature.coherence-distributed-configuration.micronaut.documentation
  - io.micronaut.starter.feature.coherence-docs
---
type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.coherence-distributed-configuration.dependencies
displayName: Add Coherence Distributed Configuration dependency
recipeList:
  - org.openrewrite.java.dependencies.AddDependency:
      groupId: io.micronaut.coherence
      artifactId: micronaut-coherence-distributed-configuration
      configuration: implementation
      scope: compile
---
type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.coherence-distributed-configuration.micronaut.documentation
displayName: Append a link to Micronaut Coherence Distributed Configuration documentation
recipeList:
  - org.openrewrite.text.AppendToTextFile:
      relativeFileName: README.md
      content: https://micronaut-projects.github.io/micronaut-coherence/latest/guide/#distributedConfiguration
      appendNewline: true



