type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.data-config-h2
displayName: Add Data H2 configuration
recipeList:
  - io.micronaut.starter.feature.create-application-properties
  - io.micronaut.starter.feature.data-config-h2.config
---
type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.data-config-h2.config
displayName: Add Data H2 configuration
preconditions:
  - io.micronaut.starter.openrewrite.recipes.FindApplicationProperties
recipeList:
  - org.openrewrite.properties.AddProperty:
      property: datasources.default.dialect
      value: H2
