type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.jdbc-config-mariadb
displayName: Add Jdbc Mariadb configuration
recipeList:
  - io.micronaut.starter.feature.create-application-properties
  - io.micronaut.starter.feature.jdbc-config-mariadb.config
---
type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.jdbc-config-mariadb.config
displayName: Add Jdbc Mariadb configuration
preconditions:
  - io.micronaut.starter.openrewrite.recipes.FindApplicationProperties
recipeList:
  - org.openrewrite.properties.AddProperty:
      property: datasources.default.db-type
      value: mariadb
  - org.openrewrite.properties.AddProperty:
      property: datasources.default.driver-class-name
      value: org.mariadb.jdbc.Driver

