type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.r2dbc-config-mysql
displayName: Add R2dbc Mysql driver configuration
preconditions:
  - io.micronaut.starter.openrewrite.recipes.FindApplicationProperties
recipeList:
  - org.openrewrite.properties.AddProperty:
      property: r2dbc.datasources.default.dialect
      value: MYSQL
  - org.openrewrite.properties.AddProperty:
      property: r2dbc.datasources.default.db-type
      value: mysql
