type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.swagger-ui-docs
displayName: Add Swagger Ui documentation
recipeList:
  - io.micronaut.starter.feature.swagger-ui-docs.micronaut.documentation
  - io.micronaut.starter.feature.swagger-ui-docs.documentation.thirdparty
---
type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.swagger-ui-docs.micronaut.documentation
displayName: Append a link to Micronaut Swagger Ui documentation
recipeList:
  - org.openrewrite.text.AppendToTextFile:
      relativeFileName: README.md
      content: https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html
      appendNewline: true
      existingFileStrategy: Continue
---
type: specs.openrewrite.org/v1beta/recipe
name: io.micronaut.starter.feature.swagger-ui-docs.documentation.thirdparty
displayName: Append a link to Swagger Ui website
recipeList:
  - org.openrewrite.text.AppendToTextFile:
      relativeFileName: README.md
      content: https://swagger.io/tools/swagger-ui/
      appendNewline: true
      existingFileStrategy: Continue
